name: ansible_workflow

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS User Credentials.
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS User Credentials.
  EC2_PRIVATE_SSH_KEY: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }} # Used to ssh into EC2.
  EC2_PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_PUBLIC_KEY }} # Used to upload public key to aws.
  AWS_REGION: eu-south-1

jobs:
  ansible:
    runs-on: ubuntu-latest
    # outputs: # used to reference in later job
    #   BASTION_PUBLIC_IP: ${{ steps.get-public-ip.outputs.bastion_public_ip}}
    steps:
    - uses: actions/checkout@v3

    - run: terraform init

    - name: Terraform Apply
      run: |
        terraform apply \
        -var="public_key=$EC2_PUBLIC_SSH_KEY" \
        -var="key_name=ssh_key_aws" \
        -auto-approve

    - name: Set ENV 1
      id: get-public-ip
      run: echo "bastion_public_ip=$(terraform output bastion_public_ip)" >> $GITHUB_ENV
    
    - name: Install Ansible
      run: |
        sudo yum update -y
        sudo amazon-linux-extras install ansible2 -y

    - name: Run Ansible Command
      env:
        #BASTION_PUBLIC_IP: ${{ steps.get-public-ip.outputs.bastion_public_ip}}
        BASTION_PUBLIC_IP: ${{ env.bastion_public_ip}}
      run: |
        ansible webserver -m ping --extra-vars "ansible_host=$BASTION_PUBLIC_IP ansible_ssh_private_key_file=$EC2_PRIVATE_SSH_KEY"
      working-directory: ./Ansible