name: ansible_workflow

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS User Credentials.
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS User Credentials.
  EC2_PRIVATE_SSH_KEY: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }} # Used to ssh into EC2.
  EC2_PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_PUBLIC_KEY }} # Used to upload public key to aws.
  AWS_REGION: us-east-1

jobs:
  ansible:
    runs-on: ubuntu-latest
    # outputs: # used to reference in later job
    #   BASTION_PUBLIC_IP: ${{ steps.get-public-ip.outputs.bastion_public_ip}}
    steps:
    - uses: actions/checkout@v3

    - run: terraform init

    - name: Terraform Apply
      run: |
        terraform apply \
        -var="public_key=$EC2_PUBLIC_SSH_KEY" \
        -var="key_name=ssh_key_aws" \
        -auto-approve

    - name: Set ENV 1
      id: get-public-ip
      run: echo "bastion_public_ip=$(terraform output bastion_public_ip)" >> $GITHUB_ENV
    
    # this task will be used with build and push not when pull and run.
    # - name: Login to AWS ECR Public
    #   id: login-ecr-public
    #   uses: aws-actions/amazon-ecr-login@v1    
    #   with:
    #     registry-type: public

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt -y install ansible

    - name: Run Ansible Command
      # env:
      #   #BASTION_PUBLIC_IP: ${{ steps.get-public-ip.outputs.bastion_public_ip}}
      #   BASTION_PUBLIC_IP: ${{ env.bastion_public_ip}}
      run: |
        echo "$EC2_PRIVATE_SSH_KEY" > ssh_key_aws.pem
        sudo chmod 400 ssh_key_aws.pem
        ansible-playbook docker_playbook.yml --extra-vars "ansible_host=$bastion_public_ip"
      working-directory: ./Ansible
